# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Generic repository security scan

on:
  push:
    branches:
      # Don't run on _every_ branch, but do make it available if there is any direct push
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
   scan-repo:
    uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@latest
